<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Academic Head Reports PDF | USTP DMCRS</title>
    <style>
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 10px;
            color: #1f2937;
            margin: 0;
            padding: 15px;
        }
        
        .header {
            background: #023047;
            color: #fff;
            padding: 15px 20px;
            margin: -15px -15px 20px -15px;
            border-radius: 0;
        }
        
        .header-content {
            display: flex;
            align-items: center;
            gap: 12px;
        }
        
        .logo-circle {
            width: 40px;
            height: 40px;
            background: #ffc107;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            font-size: 18px;
            color: #023047;
        }
        
        .header-title {
            font-size: 20px;
            font-weight: 700;
            margin: 0;
        }
        
        .header-subtitle {
            font-size: 10px;
            opacity: 0.9;
            margin-top: 2px;
        }
        
        .meta-info {
            background: #f3f4f6;
            padding: 10px 12px;
            border-radius: 4px;
            margin-bottom: 15px;
            font-size: 9px;
        }
        
        .meta-item {
            margin: 3px 0;
        }
        
        .meta-item strong {
            color: #023047;
        }
        
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 15px;
        }
        
        .stat-row {
            display: table-row;
        }
        
        .stat-card {
            display: table-cell;
            background: #f9fafb;
            border: 1px solid #e5e7eb;
            border-left: 3px solid #023047;
            padding: 8px;
            width: 25%;
            vertical-align: top;
        }
        
        .stat-label {
            font-size: 8px;
            color: #6b7280;
            text-transform: uppercase;
            margin-bottom: 3px;
        }
        
        .stat-value {
            font-size: 14px;
            font-weight: 700;
            color: #023047;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        
        thead {
            background: #023047;
            color: #fff;
        }
        
        th {
            padding: 8px 6px;
            text-align: left;
            font-weight: 600;
            font-size: 9px;
            text-transform: uppercase;
            border-right: 1px solid rgba(255,255,255,0.2);
        }
        
        th:last-child {
            border-right: none;
        }
        
        td {
            padding: 6px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 9px;
        }
        
        tbody tr:nth-child(even) {
            background: #f9fafb;
        }
        
        .badge {
            display: inline-block;
            padding: 3px 6px;
            border-radius: 10px;
            font-size: 8px;
            font-weight: 600;
            text-transform: uppercase;
        }
        
        .badge.approved { background: #d1fae5; color: #065f46; }
        .badge.rejected { background: #fee2e2; color: #991b1b; }
        .badge.pending { background: #e0e7ff; color: #3730a3; }
        .badge.other { background: #fef3c7; color: #92400e; }
        
        .footer {
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            font-size: 8px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="header-content">
            <div class="logo-circle">U</div>
            <div>
                <div class="header-title">USTP DMCRS</div>
                <div class="header-subtitle">Digital Makeup Class Request System</div>
            </div>
        </div>
    </div>

    <div class="meta-info">
        <div class="meta-item"><strong>Report:</strong> Academic Head Reports</div>
        <div class="meta-item"><strong>Generated By:</strong> {{ $generatedBy }}</div>
        <div class="meta-item"><strong>Generated:</strong> {{ $generatedAt->format('F d, Y g:i A') }}</div>
        <div class="meta-item"><strong>Total Reports:</strong> {{ count($reports) }}</div>
    </div>

    @php
        $approvedCount = collect($reports)->where('final_status', 'approved')->count();
        $rejectedCount = collect($reports)->where('final_status', 'rejected')->count();
        $pendingCount = collect($reports)->where('final_status', 'pending')->count();
    @endphp

    <div class="stats-grid">
        <div class="stat-row">
            <div class="stat-card">
                <div class="stat-label">Total</div>
                <div class="stat-value">{{ count($reports) }}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Approved</div>
                <div class="stat-value" style="color: #065f46;">{{ $approvedCount }}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Rejected</div>
                <div class="stat-value" style="color: #991b1b;">{{ $rejectedCount }}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Pending</div>
                <div class="stat-value" style="color: #3730a3;">{{ $pendingCount }}</div>
            </div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Faculty</th>
                <th>Tracking #</th>
                <th>Subject</th>
                <th>Date</th>
                <th>Time</th>
                <th>Room</th>
                <th>Reason</th>
                <th>Status</th>
                <th>Approved Date</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reports as $i => $r)
            @php
                $status = strtolower($r->final_status ?? 'pending');
                $statusClass = in_array($status, ['approved', 'rejected', 'pending']) ? $status : 'other';
                $fmt = function($t) {
                    if(!$t) return '';
                    $f = substr_count($t, ':') === 2 ? 'H:i:s' : 'H:i';
                    try {
                        return \Carbon\Carbon::createFromFormat($f, $t)->format('g:i A');
                    } catch(Exception $e) {
                        return $t;
                    }
                };
            @endphp
            <tr>
                <td><strong>{{ $i + 1 }}</strong></td>
                <td>{{ $r->faculty }}</td>
                <td><strong>{{ $r->tracking_number ?? '—' }}</strong></td>
                <td>{{ $r->subject }}</td>
                <td>{{ $r->preferred_date ? \Carbon\Carbon::parse($r->preferred_date)->format('M d, Y') : '—' }}</td>
                <td>{{ $r->preferred_time ? $fmt($r->preferred_time) : '—' }}</td>
                <td>{{ $r->room ?? '—' }}</td>
                <td>{{ Str::limit($r->reason ?? '—', 35) }}</td>
                <td>
                    <span class="badge {{ $statusClass }}">
                        {{ ucfirst($status) }}
                    </span>
                </td>
                <td>{{ $r->date_approved ? \Carbon\Carbon::parse($r->date_approved)->format('M d, Y g:i A') : '—' }}</td>
                <td>{{ Str::limit($r->remarks ?? '—', 25) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is a system-generated report from USTP Digital Makeup Class Request System (DMCRS)</p>
        <p>Generated on {{ $generatedAt->format('F d, Y \a\t g:i A') }}</p>
    </div>
</body>
</html>
