<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ ucfirst($type) }} Report - USTP DMCRS</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 10px; }
        h1 { color: #023047; font-size: 18px; margin-bottom: 10px; }
        h2 { color: #023047; font-size: 14px; margin-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #023047; color: white; padding: 8px; text-align: left; font-weight: bold; }
        td { border: 1px solid #ddd; padding: 6px; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .header { margin-bottom: 20px; }
        .footer { margin-top: 20px; font-size: 8px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ ucfirst($type) }} Report</h1>
        <p><strong>Generated:</strong> {{ $generatedAt->format('F d, Y g:i A') }}</p>
        <p><strong>Generated By:</strong> {{ $generatedBy }}</p>
    </div>

    <table>
        <thead>
            <tr>
                @if($type == 'users')
                    <th>Name</th><th>Email</th><th>Role</th><th>Department</th><th>Status</th>
                @elseif($type == 'departments')
                    <th>Name</th><th>Users</th><th>Subjects</th><th>Sections</th><th>Students</th>
                @elseif($type == 'subjects')
                    <th>Subject Code</th><th>Title</th><th>Department</th>
                @elseif($type == 'sections')
                    <th>Section</th><th>Year Level</th><th>Department</th>
                @elseif($type == 'schedules')
                    <th>Subject</th><th>Section</th><th>Day</th><th>Time</th><th>Room</th><th>Instructor</th>
                @elseif($type == 'rooms')
                    <th>Name</th><th>Capacity</th>
                @elseif($type == 'students')
                    <th>Student ID</th><th>Name</th><th>Email</th><th>Department</th><th>Year Level</th><th>Section</th><th>Status</th>
                @endif
            </tr>
        </thead>
        <tbody>
            @foreach($data as $item)
                <tr>
                    @if($type == 'users')
                        <td>{{ $item->name }}</td>
                        <td>{{ $item->email }}</td>
                        <td>{{ ucfirst(str_replace('_', ' ', $item->role)) }}</td>
                        <td>{{ $item->department->name ?? 'N/A' }}</td>
                        <td>{{ $item->is_active ? 'Active' : 'Inactive' }}</td>
                    @elseif($type == 'departments')
                        <td>{{ $item->name }}</td>
                        <td>{{ $item->users_count ?? 0 }}</td>
                        <td>{{ $item->subjects_count ?? 0 }}</td>
                        <td>{{ $item->sections_count ?? 0 }}</td>
                        <td>{{ $item->students_count ?? 0 }}</td>
                    @elseif($type == 'subjects')
                        <td>{{ $item->subject_code }}</td>
                        <td>{{ $item->subject_title }}</td>
                        <td>{{ $item->department->name ?? 'N/A' }}</td>
                    @elseif($type == 'sections')
                        <td>{{ $item->full_name ?? ($item->year_level . $item->section_name) }}</td>
                        <td>{{ $item->year_level }}</td>
                        <td>{{ $item->department->name ?? 'N/A' }}</td>
                    @elseif($type == 'schedules')
                        <td>{{ $item->subject_code }}</td>
                        <td>{{ $item->section }}</td>
                        <td>{{ $item->day_of_week }}</td>
                        <td>
                            {{ $item->time_start ? \Carbon\Carbon::parse($item->time_start)->format('g:i A') : '' }}
                            @if($item->time_end)
                                - {{ \Carbon\Carbon::parse($item->time_end)->format('g:i A') }}
                            @endif
                        </td>
                        <td>{{ $item->room }}</td>
                        <td>{{ $item->instructor ? $item->instructor->name : ($item->instructor_name ?? 'N/A') }}</td>
                    @elseif($type == 'rooms')
                        <td>{{ $item->name }}</td>
                        <td>{{ $item->capacity ?? 'N/A' }}</td>
                    @elseif($type == 'students')
                        <td>{{ $item->student_id_number }}</td>
                        <td>{{ $item->full_name ?? ($item->first_name . ' ' . $item->last_name) }}</td>
                        <td>{{ $item->email }}</td>
                        <td>{{ $item->department->name ?? 'N/A' }}</td>
                        <td>{{ $item->year_level }}</td>
                        <td>{{ $item->section ? ($item->section->full_name ?? $item->section->section_name) : 'N/A' }}</td>
                        <td>{{ ucfirst($item->status) }}</td>
                    @endif
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Records: {{ $data->count() }}</p>
        <p>USTP Balubal Campus - Department Makeup Class Request System (DMCRS)</p>
    </div>
</body>
</html>


